<a href="https://colab.research.google.com/github/lourrosaa/TP-Grupal-Analisis/blob/Clara-Brunch/TP_analisis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cargamos datos, importamos las librerias necesarias para el analisis y la carga del arhivo CSV. Mostrando la informacion principal del Dataframe con las primeras y ultimas filas, cantidad de filas y columnas, datos vacios y filas repetidas. Printeamos cada cosa para que no ejecute solo el ultimo codigo que le pedimos.

In [ ]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/lourrosaa/TP-Grupal-Analisis/main/sephora_website_dataset.csv")
df.head() #para primeras filas (5 por defecto)
print(df.head())
df.tail() #para las ultimas
print(df.tail())
df.shape #cuenta filas y columnas
print(df.shape)
df.dtypes #tipo de dato por columna
print(df.dtypes)
df.isnull().sum() #cantidad de valores nulos por columna
print(df.isnull().sum())

        id           brand   category                            name  \
0  2218774  Acqua Di Parma  Fragrance  Blu Mediterraneo MINIATURE Set
1  2044816  Acqua Di Parma    Cologne                         Colonia
2  1417567  Acqua Di Parma    Perfume                Arancia di Capri
3  1417617  Acqua Di Parma    Perfume                Mirto di Panarea
4  2218766  Acqua Di Parma  Fragrance           Colonia Miniature Set

             size  rating  number_of_reviews  love  price  value_price  ...  \
0  5 x 0.16oz/5mL     4.0                  4  3002   66.0         75.0  ...
1   0.7 oz/ 20 mL     4.5                 76  2700   66.0         66.0  ...
2    5 oz/ 148 mL     4.5                 26  2600  180.0        180.0  ...
3   2.5 oz/ 74 mL     4.5                 23  2900  120.0        120.0  ...
4  5 x 0.16oz/5mL     3.5                  2   943   72.0         80.0  ...

  MarketingFlags  MarketingFlags_content  \
0           True             online only
1           True             online only
2           True             online only
3           True             online only
4           True             online only

                                             options  \
0                                         no options
1   - 0.7 oz/ 20 mL  Spray  - 1.7 oz/ 50 mL Eau d...
2   - 1oz/30mL Eau de Toilette  - 2.5 oz/ 74 mL E...
3   - 1 oz/ 30 mL Eau de Toilette Spray - 2.5 oz/...
4                                         no options

                                             details  \
0  This enchanting set comes in a specially handc...
1  An elegant timeless scent filled with a fresh-...
2  Fragrance Family: Fresh Scent Type: Fresh Citr...
3  Panarea near Sicily is an an island suspended ...
4  The Colonia Miniature Set comes in an iconic A...

                                          how_to_use  \
0  Suggested Usage:-Fragrance is intensified by t...
1                                    no instructions
2                                    no instructions
3                                    no instructions
4  Suggested Usage:-Fragrance is intensified by t...

                                         ingredients online_only  exclusive  \
0  Arancia di Capri Eau de Toilette: Alcohol Dena...           1          0
1                                            unknown           1          0
2  Alcohol Denat.- Water- Fragrance- Limonene- Li...           1          0
3                                            unknown           1          0
4  Colonia: Alcohol Denat.- Water- Fragrance- Lim...           1          0

   limited_edition  limited_time_offer
0                0                   0
1                0                   0
2                0                   0
3                0                   0
4                0                   0

[5 rows x 21 columns]
           id               brand            category  \
9163  2208502  SEPHORA COLLECTION          Face Masks
9164  2298909  SEPHORA COLLECTION            Lip Sets
9165  2236750  SEPHORA COLLECTION  Tinted Moisturizer
9166       50  SEPHORA COLLECTION         no category
9167      304  SEPHORA COLLECTION         no category

                                            name              size  rating  \
9163                          The Rose Gold Mask           no size     2.0
9164  Give Me Some Sugar Colorful Gloss Balm Set  3 x 0.32 oz/ 9 g     0.0
9165               Weekend Warrior Tone Up Cream   0.946 oz/ 28 mL     0.0
9166                                   Gift Card           no size     5.0
9167                    Happy Birthday Gift Card           no size     0.0

      number_of_reviews  love  price  value_price  ... MarketingFlags  \
9163                 15  6200    6.0          6.0  ...           True
9164                  0   266   15.0         27.0  ...           True
9165                  0   445   16.0         16.0  ...           True
9166                 46     0   50.0         50.0  ...          False
9167                  0     0   50.0         50.0  ...          False

           MarketingFlags_content     options  \
9163  limited edition · exclusive  no options
9164                    exclusive  no options
9165                    exclusive  no options
9166                            0  no options
9167                            0  no options

                                                details  \
9163  What it is: A limited-edition- nurturing and h...
9164  What it is: A set of three bestselling Colorfu...
9165  What it is: A weightless complexion booster- i...
9166  What it is:- Available in denominations of $10...
9167  What it is:\n- Available in denominations of $...

                                             how_to_use  \
9163  Suggested Usage:-Unfold the mask.-Apply the ma...
9164  Suggested Usage:-Apply directly to lips using ...
9165  Suggested Usage:-Use this product as the last ...
9166                                    no instructions
9167                                    no instructions

                                            ingredients online_only  \
9163  -Rose Quartz Extract: Hydrates dry skin.  Aqua...           0
9164  Colorful Gloss Balm Wanderlust: Hydrogenated P...           0
9165  Aqua (Water)- Dimethicone- Isohexadecane- Poly...           0
9166                                            unknown           0
9167                                            unknown           0

      exclusive  limited_edition  limited_time_offer
9163          1                1                   0
9164          1                0                   0
9165          1                0                   0
9166          0                0                   0
9167          0                0                   0

[5 rows x 21 columns]
(9168, 21)
id                          int64
brand                      object
category                   object
name                       object
size                       object
rating                    float64
number_of_reviews           int64
love                        int64
price                     float64
value_price               float64
URL                        object
MarketingFlags               bool
MarketingFlags_content     object
options                    object
details                    object
how_to_use                 object
ingredients                object
online_only                 int64
exclusive                   int64
limited_edition             int64
limited_time_offer          int64
dtype: object
id                        0
brand                     0
category                  0
name                      0
size                      0
rating                    0
number_of_reviews         0
love                      0
price                     0
value_price               0
URL                       0
MarketingFlags            0
MarketingFlags_content    0
options                   0
details                   0
how_to_use                0
ingredients               0
online_only               0
exclusive                 0
limited_edition           0
limited_time_offer        0
dtype: int64

Podemos ver que en este Dataset que importamos de Sephora no se detectaron valores nulos. Además de que la mayoria de datos son de texto o de números enteros, con solo pocas excepciones.

###Revisión adicional de la estructura y calidad de datos
Se muestran los nombres de todas las columnas para identificar las variables disponibles. Se cuentan las filas completamente duplicadas para detectar posibles registros repetidos y se calculan estadísticas descriptivas generales.

In [23]:
print("Columnas del dataset:")
print(df.columns.tolist())

print("\nCantidad de filas completamente duplicadas:")
print(df.duplicated().sum())

display(df.describe())

Columnas del dataset:
['id', 'brand', 'category', 'name', 'size', 'rating', 'number_of_reviews', 'love', 'price', 'value_price', 'URL', 'MarketingFlags', 'MarketingFlags_content', 'options', 'details', 'how_to_use', 'ingredients', 'online_only', 'exclusive', 'limited_edition', 'limited_time_offer']

Cantidad de filas completamente duplicadas:
0

,id,rating,number_of_reviews,love,price,value_price,online_only,exclusive,limited_edition,limited_time_offer
count,9.168000e+03,9168.000000,9168.000000,9.168000e+03,9168.000000,9168.00000,9168.000000,9168.000000,9168.000000,9168.000000
mean,1.962952e+06,3.990020,282.139180,1.627859e+04,50.063237,51.82359,0.234839,0.264725,0.091841,0.000327
std,3.859714e+05,1.007707,890.642028,4.260651e+04,47.164989,49.45902,0.423921,0.441211,0.288817,0.018087
min,5.000000e+01,0.000000,0.000000,0.000000e+00,2.000000,2.00000,0.000000,0.000000,0.000000,0.000000
25%,1.819453e+06,4.000000,10.000000,1.600000e+03,24.000000,25.00000,0.000000,0.000000,0.000000,0.000000
50%,2.072354e+06,4.000000,46.000000,4.800000e+03,35.000000,35.00000,0.000000,0.000000,0.000000,0.000000
75%,2.230591e+06,4.500000,210.000000,1.380000e+04,59.000000,60.00000,0.000000,1.000000,0.000000,0.000000
max,2.359685e+06,5.000000,19000.000000,1.300000e+06,549.000000,549.00000,1.000000,1.000000,1.000000,1.000000

###Cobertura temporal y geográfica
El dataset contiene información de productos del sitio web de Sephora, obtenida mediante web scraping y publicada en Kaggle por Raghad Alharbi.

No incluye columnas de fechas que permitan analizar la evolución de los productos. La descripción consultada tampoco especifica el país o mercado al que corresponde el catalogo por lo que no hay una cobertura geográfica concreta.

El análisis se limita a los productos y los valores registrados en el dataset.

###Hallazgos
No se detectaron filas completamente duplicadas.
Las estadísticas descriptivas muestran diferencias importantes en la distribución de las variables.

La cantidad de favoritos presenta una media aproximada de 16279 y una mediana de 4800, con un máximo de 1300000. Esta diferencia indica una distribución asimétrica. Los productos acumulan grandes cantidades de favoritos, muy superiores a las de los productos típicos.

El precio presenta una media aproximada de 50,06 y una mediana de 35, con valores entrte 2 y 549. Esto también muestra diferencias considerables entre productos.

In [ ]:
df[["limited_edition", "rating", "love"]].describe()
print(df[["limited_edition", "rating", "love"]].describe())
df["limited_edition"].value_counts()

       limited_edition       rating          love
count      9168.000000  9168.000000  9.168000e+03
mean          0.091841     3.990020  1.627859e+04
std           0.288817     1.007707  4.260651e+04
min           0.000000     0.000000  0.000000e+00
25%           0.000000     4.000000  1.600000e+03
50%           0.000000     4.000000  4.800000e+03
75%           0.000000     4.500000  1.380000e+04
max           1.000000     5.000000  1.300000e+06

limited_edition
0    8326
1     842
Name: count, dtype: int64

De los 9168 productos, solo 842 son de edicion limitada

In [ ]:
df.groupby("limited_edition")["love"].median()

limited_edition
0    5000.0
1    3000.0
Name: love, dtype: float64

De los productos en total, se ve que los normales gustan mas que los productos de edicion limitada. Sin embargo tal vez eso no sea porque sean menos queridos por los compradores, se podria deber tambien a que al ser ediciones limitadas y durar menos tiempo en el mercado tienen menos tiempo para acumular "loves", no todos alcanzan a comprarlos o simplemente las personas prefieren los productos clasicos.

In [ ]:
df_rating = df[df["rating"] > 0]
print(df_rating)
df_rating.groupby("limited_edition")["rating"].median()
print(df_rating.groupby("limited_edition")["rating"].median())

           id               brand                  category  \
0     2218774      Acqua Di Parma                 Fragrance
1     2044816      Acqua Di Parma                   Cologne
2     1417567      Acqua Di Parma                   Perfume
3     1417617      Acqua Di Parma                   Perfume
4     2218766      Acqua Di Parma                 Fragrance
...       ...                 ...                       ...
9160  2149847  SEPHORA COLLECTION  Bath Soaks & Bubble Bath
9161  1601111  SEPHORA COLLECTION                Brush Sets
9162  2149839  SEPHORA COLLECTION        Scrub & Exfoliants
9163  2208502  SEPHORA COLLECTION                Face Masks
9166       50  SEPHORA COLLECTION               no category

                                                   name            size  \
0                        Blu Mediterraneo MINIATURE Set  5 x 0.16oz/5mL
1                                               Colonia   0.7 oz/ 20 mL
2                                      Arancia di Capri    5 oz/ 148 mL
3                                      Mirto di Panarea   2.5 oz/ 74 mL
4                                 Colonia Miniature Set  5 x 0.16oz/5mL
...                                                 ...             ...
9160          Fizzing Bath Star Mini - Surprise Flowers      0.53oz/15g
9161                  Face the Day: Full Face Brush Set         no size
9162  Exfoliating Body Granita Scrub - Surprise Flowers    8.45oz/250mL
9163                                 The Rose Gold Mask         no size
9166                                          Gift Card         no size

      rating  number_of_reviews   love  price  value_price  ...  \
0        4.0                  4   3002   66.0         75.0  ...
1        4.5                 76   2700   66.0         66.0  ...
2        4.5                 26   2600  180.0        180.0  ...
3        4.5                 23   2900  120.0        120.0  ...
4        3.5                  2    943   72.0         80.0  ...
...      ...                ...    ...    ...          ...  ...
9160     3.5                 11   2100    2.0          2.0  ...
9161     3.5                 62  32900   49.0         95.0  ...
9162     3.5                 39   6900    8.0          8.0  ...
9163     2.0                 15   6200    6.0          6.0  ...
9166     5.0                 46      0   50.0         50.0  ...

     MarketingFlags       MarketingFlags_content  \
0              True                  online only
1              True                  online only
2              True                  online only
3              True                  online only
4              True                  online only
...             ...                          ...
9160           True      exclusive · online only
9161           True  limited edition · exclusive
9162           True      exclusive · online only
9163           True  limited edition · exclusive
9166          False                            0

                                                options  \
0                                            no options
1      - 0.7 oz/ 20 mL  Spray  - 1.7 oz/ 50 mL Eau d...
2      - 1oz/30mL Eau de Toilette  - 2.5 oz/ 74 mL E...
3      - 1 oz/ 30 mL Eau de Toilette Spray - 2.5 oz/...
4                                            no options
...                                                 ...
9160                                         no options
9161                                         no options
9162                                         no options
9163                                         no options
9166                                         no options

                                                details  \
0     This enchanting set comes in a specially handc...
1     An elegant timeless scent filled with a fresh-...
2     Fragrance Family: Fresh Scent Type: Fresh Citr...
3     Panarea near Sicily is an an island suspended ...
4     The Colonia Miniature Set comes in an iconic A...
...                                                 ...
9160  What it is:  A fizzing star that dissolves int...
9161  What it is:\nA six-piece brush set designed to...
9162  What it is:  An indulgent- yet gentle exfoliat...
9163  What it is: A limited-edition- nurturing and h...
9166  What it is:- Available in denominations of $10...

                                             how_to_use  \
0     Suggested Usage:-Fragrance is intensified by t...
1                                       no instructions
2                                       no instructions
3                                       no instructions
4     Suggested Usage:-Fragrance is intensified by t...
...                                                 ...
9160  Suggested Usage:-Place the fizzing star in the...
9161                                    no instructions
9162  Suggested Usage:-Apply to wet skin.-Massage in...
9163  Suggested Usage:-Unfold the mask.-Apply the ma...
9166                                    no instructions

                                            ingredients online_only  \
0     Arancia di Capri Eau de Toilette: Alcohol Dena...           1
1                                               unknown           1
2     Alcohol Denat.- Water- Fragrance- Limonene- Li...           1
3                                               unknown           1
4     Colonia: Alcohol Denat.- Water- Fragrance- Lim...           1
...                                                 ...         ...
9160  Sodium Bicarbonate- Citric Acid- CI 77891 (Tit...           1
9161                                            unknown           0
9162  Water- Glycerin- Cellulose Acetate- Sodium Lau...           1
9163  -Rose Quartz Extract: Hydrates dry skin.  Aqua...           0
9166                                            unknown           0

      exclusive  limited_edition  limited_time_offer
0             0                0                   0
1             0                0                   0
2             0                0                   0
3             0                0                   0
4             0                0                   0
...         ...              ...                 ...
9160          1                0                   0
9161          1                1                   0
9162          1                0                   0
9163          1                1                   0
9166          0                0                   0

[8770 rows x 21 columns]
limited_edition
0    4.5
1    4.5
Name: rating, dtype: float64

Aca vemos que no solo las ediciones limitadas tienen menos love que los productos normales, sino que tiene el mismo promedio de rating. Asi que por ahora no vemos que las ediciones limitadas gusten mas que las regulares.